chore: refactor fork Taskfiles

diff --git a/dist/fork/Taskfile b/dist/fork/Taskfile
--- a/dist/fork/Taskfile
+++ b/dist/fork/Taskfile
@@ -1,28 +1,11 @@
 #!/usr/bin/env bash
 
+set -euo pipefail
+
 [ "${BASH_VERSINFO:-0}" -ge 4 ] || {
   echo "bash version 4 or higher is required" >&2
   exit 1
 }
-
-set -euo pipefail
-
-# How to use it
-#  - run patch
-#  - run --increment patch
-#  - run patch vX.Y.Z
-#  - run --increment patch vX.Y.Z
-#  - run patch -- vA.B.C
-#  - run --increment patch -- vA.B.C
-#  - run patch vX.Y.Z -- vA.B.C
-#  - run --increment patch vX.Y.Z -- vA.B.C
-#  - run -d patch vX.Y.Z -- vA.B.C > bin/transaction.bash
-#  - run release
-#  - run --increment release
-#  - run release vX.Y.Z
-#  - run --increment release vX.Y.Z
-#  - run -d release vX.Y.Z > bin/transaction.bash
-#  - run -d --increment release vX.Y.Z > bin/transaction.bash
 
 declare -A config
 config['branch']=extended
@@ -38,19 +21,22 @@ remotes['origin']="git@github.com:${config['source']}.git"
 remotes['upstream']=git@github.com:upstream/source.git
 order=(origin upstream)
 
-function amend() {
+@amend() {
   local _ad _cd
   _ad=$(git --no-pager log -1 --format="%aI")
   _cd=$(git --no-pager log -1 --format="%cI")
-  GIT_COMMITTER_DATE="${_cd}" git commit --amend --date="${_ad}" --no-edit "${@}"
+  _ eval GIT_COMMITTER_DATE="${_cd}" git commit --amend --date="${_ad}" --no-edit
 }
 
-function check() {
+@check() {
+  git diff --exit-code >/dev/null
+  git diff --cached --exit-code >/dev/null
+  git ls-files --others --exclude-standard | grep -q ^ && return 1
   [ "$(git rev-parse --abbrev-ref HEAD)" == "${config['branch']}" ]
   [ "${#remotes[@]}" == "${#order[@]}" ]
 }
 
-function clean() {
+@clean() {
   # we have to delete remote branches
   git branch -a | grep remotes/ |
     # except upstream' branches,
@@ -61,7 +47,7 @@ function clean() {
     sed 's|remotes/||g' |
     sed 's|/| |' |
     # bat -P && return | # debug pipe before deleting branches
-    prune || true
+    @prune || true
 
   # we have to delete useless tags
   git tag --list |
@@ -70,119 +56,77 @@ function clean() {
     # exclude the reason
     grep -v "${config['reason']}" |
     # bat -P && return | # debug pipe before deleting tags
-    untag || true
+    @untag || true
 }
 
-function fetch() {
+@fetch() {
   for remote in "${order[@]}"; do
-    _ git fetch "${remote}" --force --prune --tags
+    @ git fetch "${remote}" --force --prune --tags
   done
 }
 
-function patch() {
-  local vendor=latest version
-
-  case "${#}" in
-  3)
-    version=${1}
-    vendor=${3}
-    ;;
-  2) vendor=${2} ;;
-  1) version=${1} ;;
-  esac
-
-  _ git rebase -i "${config['reason']}"
-  _ go mod edit -require="${config['vendor']}@${vendor}"
-  _ go mod tidy
-  _ git add .
-  _ amend
-  _ git rebase --continue
-  release "${version:-$(version)}"
-}
-
-function prune() {
+@prune() {
   local remote branch
   while read -r remote branch; do
     _ git push -d "${remote}" "${branch}"
   done
 }
 
-function setup() {
-  for remote in $(git remote -v | awk '{print $1}' | sort | uniq); do
-    _ git remote rm "${remote}"
+@setup() {
+  for remote in "${!remotes[@]}"; do
+    local url
+    url=$(git remote get-url --push "${remote}" 2>/dev/null || echo -n)
+
+    if [ -z "${url}" ]; then
+      echo "remote ${remote} not found and will be added"
+      _ git remote add "${remote}" "${remotes[$remote]}"
+    elif [ "${url}" != "${remotes[$remote]}" ]; then
+      echo "remote ${remote} (${url}) is unknown and will be replaced"
+      _ git remote set-url "${remote}" "${remotes[$remote]}"
+    fi
   done
 
-  for remote in "${!remotes[@]}"; do
-    _ git remote add "${remote}" "${remotes[$remote]}"
+  for remote in $(git remote); do
+    if [ -z "${remotes[$remote]-}" ]; then
+      echo "remote ${remote} ($(git remote get-url --push "${remote}")) is unknown and will be deleted"
+      _ git remote rm "${remote}"
+    fi
   done
 }
 
-function untag() {
+@untag() {
+  declare -A tags
+  for remote in $(git remote | grep -v upstream); do
+    tags[${remote}]=$(git ls-remote -q --tags "${remote}" | grep -v '{}' | awk -F/ '{print $3}')
+  done
+
   local tag
   while read -r tag; do
-    _ git tag -d "${tag}" || true
+    + git tag -d "${tag}"
     for remote in $(git remote | grep -v upstream); do
-      _ git push "${remote}" :refs/tags/"${tag}" || true
+      echo "${tags[${remote}]}" | grep -q "^${tag}$" || continue
+      + git push "${remote}" :refs/tags/"${tag}"
     done
   done
 }
 
-function publish() {
+@publish() {
   local version=${1}
-  _ gh release -R "${config['source']}" delete "${version}" -y || true
+  + gh release -R "${config['source']}" delete "${version}" -y
   _ gh release -R "${config['source']}" edit "${config['reason']}" --draft=false --prerelease
   _ goreleaser --clean --release-notes CHANGES.md
   _ rm -rf dist
   _ gh release -R "${config['source']}" view "${version}" -w
 }
 
-function release() {
-  check
-  fetch
-  clean
-
-  # define the release version: passed or latest,
-  # and it's commit to creating the new tag on it
-  local version=${1:-$(version)}
-
-  # prepare release
-  local fork
-  fork=$(git merge-base --fork-point "${version}" 2>/dev/null || git rev-list -n1 "${version}")
-  _ git rebase --onto "${version}" "${config['target']}"
-  if ${config['detach']}; then
-    version=$(increment "${version}")
-  else
-    untag <<<"${version}"
-  fi
-  _ git tag -m "'sync with upstream'" "${version}"
-  untag <<<"${config['reason']}"
-  _ git tag -m "'extend by ${config['reason']}'" "${config['reason']}" "${fork}"
-
-  # do release
-  for remote in $(git remote | grep -v upstream); do
-    _ git push --force-with-lease "${remote}" "${config['branch']}"
-    _ git push "${remote}" "refs/tags/${config['reason']}"
-    _ git push "${remote}" "refs/tags/${version}"
-  done
-  publish "${version}"
-
-  # add build metadata
-  if ${config['detach']}; then return; fi
-  local revision
-  revision=$(git rev-parse --short HEAD)
-  _ git tag -m "'specific build version'" "${version}+${revision}"
-  for remote in $(git remote | grep -v upstream); do
-    _ git push "${remote}" "refs/tags/${version}+${revision}"
-  done
-}
-
-function version() {
-  git ls-remote --tags --sort=-v:refname "${remotes['upstream']}" |
+@version() {
+  git ls-remote -q --sort=-v:refname --tags upstream |
+    grep -v '{}' |
     head -1 |
     awk -F/ '{print $3}'
 }
 
-function increment() {
+@increment() {
   local latest=${1} prefix
   prefix=$(echo "${latest}" | awk -F. '{NF--} 1' | sed 's/ /./g')
   git tag --list --sort=-v:refname |
@@ -192,18 +136,10 @@ function increment() {
     sed 's/ /./g'
 }
 
-function installer() {
+@installer() {
   godownloader .goreleaser.yml >bin/install
 }
 
-_() {
-  if ${config['dryrun']}; then
-    echo "${@}"
-    return
-  fi
-  trap 'echo "${@}"' ERR
-  "${@}"
-}
 @debug() { echo "${@}"; }
 @trace() { @debug "${@}" && "${@}"; }
 @error() { echo "${@}" >&2; }
@@ -216,10 +152,42 @@ EOF
   compgen -A function | grep -Ev '^(@|_)' | sort | cat -n
 }
 
+@() {
+  ${config['dryrun']} && echo "${@}"
+  "${@}"
+}
+
+_() {
+  if ${config['dryrun']}; then
+    echo "${@}"
+    return
+  fi
+  trap 'echo "${@}"' ERR
+  "${@}"
+}
+
+-() {
+  if ${config['dryrun']}; then
+    echo "${*} || false"
+    return
+  fi
+  trap 'echo "${*} || false"' ERR
+  "${@}" || false
+}
+
++() {
+  if ${config['dryrun']}; then
+    echo "${*} || true"
+    return
+  fi
+  trap 'echo "${*} || true"' ERR
+  "${@}" || true
+}
+
 function @main() {
   for arg in "${@}"; do
     case "${arg}" in
-    --increment)
+    -i | --increment)
       config['detach']=true
       shift
       ;;
@@ -227,6 +195,7 @@ function @main() {
       config['dryrun']=true
       shift
       ;;
+    *) break ;;
     esac
   done
   "${@:-@usage}"
